### PR TITLE
Chip organizational update

### PR DESCRIPTION
**Pull request by hullabaloo-vincent**

### CODE REVIEW

**Review by AlexKollar — APPROVED** [review]
Tested and working on my laptop! 
Awesome update!

**Comment by AlexKollar** [comment]
Merging in! Tested, and works!

**Comment by AlexKollar** [comment]
@hullabaloo-vincent - I'll leave the branch open in case if anything gets changed around.

**Comment by hullabaloo-vincent** [comment]
@AlexKollar I might make a few small suggestions based off of the static code analysis

**Comment by AlexKollar** [comment]
> @AlexKollar I might make a few small suggestions based off of the static code analysis

Aye do yah thing @hullabaloo-vincent

**Pull request merged**
